---
title: "Hands-On Exercise 03"
description: |
 Spatial Point Pattern Analysis
author:
  - name: Khant Min Naing
    url: https://www.linkedin.com/in/khantminnaing/
date: 01-12-2024
date-modified: "last-modified"
categories:
  - In-Class Exercise
  - R
  - sf
  - lubridate
  - grab-posisi
format:
  html:  
    #code-fold: true
    code-summary: "Show the code"
execute: 
  eval: true
  echo: true
  warning: false
output:
  distill::distill_article:
    toc: true
    self_contained: false
---

# 1st and 2nd Order Spatial Point Patterns Analysis Methods

Spatial Point Pattern Analysis is the evaluation of the pattern, or distribution, of a set of points on a surface. It can refer to the actual spatial or temporal location of these points or also include data from point sources. It is one of the most fundamental concepts in geography and spatial analysis. This hands-on exercise will explore the basic concepts and methods of Spatial Point Pattern Analysis.

Particularly, we will explore using [spatstat](https://cran.r-project.org/web/packages/spatstat/), an R package specially designed for Spatial Point Pattern Analysis.

## 1.0 Overview 

Today, we will use Spatial Point Pattern Analysis to analyse the spatial point processes of childcare centers in Singapore.

The specific questions we would like to address through this exercise are as follows:

-   Are the childcare centres in Singapore randomly distributed throughout the country?

-   Where are the locations with higher concentration of childcare centres?

## 2.0 Importing Packages

## 3.0 Importing Datasets to R Environment

In this exercise, we will use the following datasets:

-   `CHILDCARE`, a point feature data providing both location and attribute information of childcare centres. It was downloaded from Data.gov.sg and is in geojson format.

-   `MP14_SUBZONE_WEB_PL`, a polygon feature data providing information of URA 2014 Master Plan Planning Subzone boundary data. It is in ESRI shapefile format. This data set was also downloaded from Data.gov.sg.

-   `CostalOutline`, a polygon feature data showing the national boundary of Singapore. It is provided by SLA and is in ESRI shapefile format.

## 1st Order Spatial Point Pattern Analysis
