<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Khant Min Naing">
<meta name="dcterms.date" content="2024-01-15">
<meta name="description" content="Application of Spatial Point Patterns Analysis to discover the geographical distribution of Grab hailing services in Singapore, implemented using spatstat package (Baddeley, Turner, and Rubak 2022) in R environment.">

<title>IS415 - Geospatial with Khant - Take-Home Exercise 01: Spatial Point Patterns Analysis of Grab Trajectories in Singapore</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">IS415 - Geospatial with Khant</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">In-Class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../In-class_Ex/In-class_Ex02.html" rel="" target="">
 <span class="dropdown-text">In-Class Exercise 02</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Hands-On Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex/hands_on1.html" rel="" target="">
 <span class="dropdown-text">Hands-On Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex/hands_on02.html" rel="" target="">
 <span class="dropdown-text">Hands-On Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex/hands_on03.html" rel="" target="">
 <span class="dropdown-text">Hands-On Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex/hands_on08.html" rel="" target="">
 <span class="dropdown-text">Hands-On Exercise 8</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../Take-home_Ex/Take-home_Ex01.html" rel="" target="">
 <span class="dropdown-text">Take-Home Exercise 01: Spatial Point Patterns Analysis of Grab Trajectories in Singapore</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Take-Home Exercise 01: Spatial Point Patterns Analysis of Grab Trajectories in Singapore</h1>
                  <div>
        <div class="description">
          <p>Application of Spatial Point Patterns Analysis to discover the geographical distribution of Grab hailing services in Singapore, implemented using spatstat package (Baddeley, Turner, and Rubak 2022) in R environment.</p>
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">grab-posisi</div>
                <div class="quarto-category">spatial point patterns</div>
                <div class="quarto-category">spatstat</div>
                <div class="quarto-category">r</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p><a href="https://www.linkedin.com/in/khantminnaing/">Khant Min Naing</a> </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 15, 2024</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">January 20, 2024</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1.0 Introduction</a></li>
  <li><a href="#literature-review-of-spatial-point-pattern-analysis" id="toc-literature-review-of-spatial-point-pattern-analysis" class="nav-link" data-scroll-target="#literature-review-of-spatial-point-pattern-analysis">2.0 Literature Review of Spatial Point Pattern Analysis</a></li>
  <li><a href="#importing-packages" id="toc-importing-packages" class="nav-link" data-scroll-target="#importing-packages">3.0 Importing Packages</a></li>
  <li><a href="#importing-datasets-into-r-environment" id="toc-importing-datasets-into-r-environment" class="nav-link" data-scroll-target="#importing-datasets-into-r-environment">4.0 Importing Datasets into R Environment</a>
  <ul class="collapse">
  <li><a href="#datasets" id="toc-datasets" class="nav-link" data-scroll-target="#datasets">4.1 Datasets</a></li>
  <li><a href="#importing-grab-posisi-dataset" id="toc-importing-grab-posisi-dataset" class="nav-link" data-scroll-target="#importing-grab-posisi-dataset">4.2 Importing Grab-Posisi Dataset</a></li>
  <li><a href="#importing-openstreetmap-road-data-for-malaysia-singapore-and-brunei" id="toc-importing-openstreetmap-road-data-for-malaysia-singapore-and-brunei" class="nav-link" data-scroll-target="#importing-openstreetmap-road-data-for-malaysia-singapore-and-brunei">4.3 Importing OpenStreetMap road data for Malaysia, Singapore and Brunei</a></li>
  <li><a href="#importing-singapore-master-plan-planning-subzone-boundary-data" id="toc-importing-singapore-master-plan-planning-subzone-boundary-data" class="nav-link" data-scroll-target="#importing-singapore-master-plan-planning-subzone-boundary-data">4.4 Importing Singapore Master Plan Planning Subzone boundary data</a></li>
  </ul></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">5.0 Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#extracting-trip-starting-locations-and-temporal-data-values-from-grab-posisi-dataset" id="toc-extracting-trip-starting-locations-and-temporal-data-values-from-grab-posisi-dataset" class="nav-link" data-scroll-target="#extracting-trip-starting-locations-and-temporal-data-values-from-grab-posisi-dataset">5.1 Extracting Trip Starting Locations and Temporal Data Values from Grab-Posisi dataset</a></li>
  <li><a href="#extracting-trip-ending-locations-and-temporal-data-values-from-grab-posisi-dataset" id="toc-extracting-trip-ending-locations-and-temporal-data-values-from-grab-posisi-dataset" class="nav-link" data-scroll-target="#extracting-trip-ending-locations-and-temporal-data-values-from-grab-posisi-dataset">5.2 Extracting Trip Ending Locations and Temporal Data Values from Grab-Posisi dataset</a></li>
  <li><a href="#converting-to-sf-tibble-data.frame" id="toc-converting-to-sf-tibble-data.frame" class="nav-link" data-scroll-target="#converting-to-sf-tibble-data.frame">5.3 Converting to sf tibble data.frame</a></li>
  <li><a href="#creating-a-coastalline-of-singapore" id="toc-creating-a-coastalline-of-singapore" class="nav-link" data-scroll-target="#creating-a-coastalline-of-singapore">5.4 Creating a CoastalLine of Singapore</a></li>
  <li><a href="#extracting-road-layers-within-singapore" id="toc-extracting-road-layers-within-singapore" class="nav-link" data-scroll-target="#extracting-road-layers-within-singapore">5.5 Extracting Road Layers within Singapore</a></li>
  <li><a href="#converting-the-simple-features-to-planar-point-pattern-object" id="toc-converting-the-simple-features-to-planar-point-pattern-object" class="nav-link" data-scroll-target="#converting-the-simple-features-to-planar-point-pattern-object">5.5 Converting the Simple Features to Planar Point Pattern Object</a></li>
  <li><a href="#handling-data-errors" id="toc-handling-data-errors" class="nav-link" data-scroll-target="#handling-data-errors">5.6 Handling Data Errors</a></li>
  <li><a href="#creating-observation-windows" id="toc-creating-observation-windows" class="nav-link" data-scroll-target="#creating-observation-windows">5.7 Creating Observation Windows</a></li>
  <li><a href="#combining-ppp-objects-and-owin-object" id="toc-combining-ppp-objects-and-owin-object" class="nav-link" data-scroll-target="#combining-ppp-objects-and-owin-object"><strong>5.8 Combining <code>ppp</code> objects and <code>owin</code> object</strong></a></li>
  </ul></li>
  <li><a href="#exploratory-spatial-data-analysis" id="toc-exploratory-spatial-data-analysis" class="nav-link" data-scroll-target="#exploratory-spatial-data-analysis">6.0 Exploratory Spatial Data Analysis</a>
  <ul class="collapse">
  <li><a href="#visualising-frequency-distribution" id="toc-visualising-frequency-distribution" class="nav-link" data-scroll-target="#visualising-frequency-distribution">6.1 Visualising Frequency Distribution</a></li>
  <li><a href="#creating-point-symbol-maps" id="toc-creating-point-symbol-maps" class="nav-link" data-scroll-target="#creating-point-symbol-maps">6.2 Creating Point Symbol Maps</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1.0 Introduction</h2>
<p>Human mobility, the spatial-temporal dynamics of human movements, serves as a critical reflection of societal patterns and human behaviors. With the advancement and pervasiveness of Information and Communication Technologies (ICT) in our daily life, especially smart phone, a large volume of data related to human mobility have been collected. These data provide valuable insights into understanding how individuals and populations move within and between different geographical locations. By using appropriate GIS analysis methods, these data can turn into valuable inisghts for predicting future mobility trrends and developing more efficient and sustainable strategies for managing urban mobility.</p>
<p>In this study, I will apply <strong>Spatial Point Patterns Analysis</strong> methods to discover the geographical and spatio-temporal distribution of Grab hailing services locations in Singapore. In order to determine the geographical and spatio-temporal patterns of the Grab hailing services, I will develop traditional <strong>Kernel Density Estimation (KDE)</strong> and <strong>Temporal Network Kernel Density Estimation (TNKDE)</strong>. KDE layers will help identify the areas with high concentration of Grab hailing services, providing insights into the demand and popularity of these services in different parts of Singapore. TNKDE, on the other hand, will allow for analysis of how the distribution of Grab hailing services changes over time, revealing temporal patterns and trends in their usage. These spatial and spatio-temporal analyses will contribute to a better understanding of the dynamics and effectiveness of Grab’s mobility services in Singapore.</p>
</section>
<section id="literature-review-of-spatial-point-pattern-analysis" class="level2">
<h2 class="anchored" data-anchor-id="literature-review-of-spatial-point-pattern-analysis">2.0 Literature Review of Spatial Point Pattern Analysis</h2>
<p>Spatial point pattern analysis is concerned with description, statistical characterization, modeling and visulisation of point patterns over space and making inference about the process that could have generated an observed pattern (Boots &amp; Getis, 1988,Rey et al., 2023; Pebesma &amp; Bivand, 2023). According to this theory, empirical spatial distribution of points in our daily life are not controlled by sampling, but a result of an <strong>underlying geographically-continuous process</strong> (Rey et al., 2023). For example, an COVID-19 cluster did not happen by chance, but due to a spatial process of close-contact infection.</p>
<p>When analysing real-world spatial points, it is important to analyse whether the observed spatial points are randomly distributed or patterned due to a process or interaction (Floch et al., 2018). In “complete random” distribution, points are located everywhere with the same probability and independently of each other. On the other hand, the spatial points can be clustered or dispersed due to an underlying point process. However, it is challenging to use heuristic observation and intuitive interpretation to detect whether a spatial point pattern exists (Baddeley et al., 2015; Floch et al., 2018). Hence, spatial point pattern analysis can be used to detect the spatial concentration or dispersion phenomena.</p>
<p><img src="images/Screenshot 2024-01-16 at 10.56.45 PM.png" class="img-fluid"></p>
<p>When analysing and interpreting the properties of a point pattern, these properties can be categorized into two: (a) first-order properties and (b) second-order properties (Yuan et al., 2020; Gimond, 2023). First-order properties concern with the characteristics of individual point locations and their variations of their density across space (Gimond, 2023). Under this conception, observations vary from point to point due to changes in the underlying property. Second-order properties focus on not only individual points, but also the interactions between points and their influences on one another (Gimond, 2023). Under this conception, observations vary from place to place due to interaction effects between observations. First-order properties of point patterns are mostly addressed by density-based techniques, such as kernel density, whereas, distance-based techniques, such nearest neighbour index and K-functions, are often used to analyse second-order properties since they take into account the distance between point pairs (Yuan et al., 2020; Gimond, 2023).</p>
</section>
<section id="importing-packages" class="level2">
<h2 class="anchored" data-anchor-id="importing-packages">3.0 Importing Packages</h2>
<p>Before we start the exercise, we will need to import necessary R packages first. We will use the following packages:</p>
<ul>
<li><p><a href="https://arrow.apache.org/docs/r/"><code>arrow</code></a> : for reading and writing Apache Parquet files</p></li>
<li><p><a href="https://lubridate.tidyverse.org/"><code>lubridate</code></a> : for tackling with temporal data (dates and times)</p></li>
<li><p><a href="https://cran.r-project.org/web/packages/spatstat/index.html"><strong><code>spatstat</code></strong></a>: A package for statistical analysis of spatial data, specifically Spatial Point Pattern Analysis. This package was provided by Baddeley, Turner and Ruback (2015) and gives a comprehensive list of functions to perform 1st- and 2nd-order spatial point patterns analysis and derive kernel density estimation (KDE) layer.</p></li>
<li><p><strong>rgdal</strong>: Used to import geospatial data and output as spatial class objects from <strong>sp</strong> package</p></li>
<li><p><strong>raster</strong> : reads, writes, manipulates, analyses and model of gridded spatial data (i.e.&nbsp;raster). In this hands-on exercise, it will be used to convert image output generate by spatstat into raster format.</p></li>
<li><p><strong>maptools</strong>, <strong>ggplot2</strong>, <strong>ggthemes</strong>, <strong>plotly</strong>: Packages used to plot interactive visualisations summary statistics and KDE layers</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(arrow,lubridate,tidyverse,tmap,sf,st,spatstat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-datasets-into-r-environment" class="level2">
<h2 class="anchored" data-anchor-id="importing-datasets-into-r-environment">4.0 Importing Datasets into R Environment</h2>
<section id="datasets" class="level3">
<h3 class="anchored" data-anchor-id="datasets">4.1 Datasets</h3>
<p>In this study, we will use <a href="https://engineering.grab.com/grab-posisi">Grab-Posisi</a> dataset, which is a comprehensive GPS trajectory dataset for car-hailing services in Southeast Asia. Apart from the time and location of the object, GPS trajectories are also characterised by other parameters such as speed, the headed direction, the area and distance covered during its travel, and the travelled time. Thus, the trajectory patterns from users GPS data are a valuable source of information for a wide range of urban applications, such as solving transportation problems, traffic prediction, and developing reasonable urban planning.</p>
<p>Moreover, we will also use <a href="https://www.geofabrik.de/geofabrik/openstreetmap.html">OpenStreetMap datase</a>t, which is an open-sourced geospatial dataset including shapefiles of important layers including road networks, forests, building footprints and many other points of interest.</p>
<p>To extract the Singapore boundary, we will use Master Plan 2019 Subzone Boundary (No Sea), provided by data.gov.sg.</p>
</section>
<section id="importing-grab-posisi-dataset" class="level3">
<h3 class="anchored" data-anchor-id="importing-grab-posisi-dataset">4.2 Importing Grab-Posisi Dataset</h3>
<p>Each trajectory in Grab-Posisi dataset is serialised in a file in Apache Parquet format. The Singapore portion of the dataset is packaged into a total of 10 Parquet files.</p>
<p>Firstly, we will use <code>read_parquet</code> function from <code>arrow</code> package, which allows us to read Parquet files into R environment as a data frame (more specifically, a <code>tibble</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">'~/IS415-GAA/data/GrabPosisi/part-00000.snappy.parquet'</span>,<span class="at">as_data_frame =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">'~/IS415-GAA/data/GrabPosisi/part-00001.snappy.parquet'</span>,<span class="at">as_data_frame =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">'~/IS415-GAA/data/GrabPosisi/part-00002.snappy.parquet'</span>,<span class="at">as_data_frame =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>df3 <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">'~/IS415-GAA/data/GrabPosisi/part-00003.snappy.parquet'</span>,<span class="at">as_data_frame =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>df4 <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">'~/IS415-GAA/data/GrabPosisi/part-00004.snappy.parquet'</span>,<span class="at">as_data_frame =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>df5 <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">'~/IS415-GAA/data/GrabPosisi/part-00005.snappy.parquet'</span>,<span class="at">as_data_frame =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>df6 <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">'~/IS415-GAA/data/GrabPosisi/part-00006.snappy.parquet'</span>,<span class="at">as_data_frame =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>df7 <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">'~/IS415-GAA/data/GrabPosisi/part-00007.snappy.parquet'</span>,<span class="at">as_data_frame =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>df8 <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">'~/IS415-GAA/data/GrabPosisi/part-00008.snappy.parquet'</span>,<span class="at">as_data_frame =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>df9 <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">'~/IS415-GAA/data/GrabPosisi/part-00009.snappy.parquet'</span>,<span class="at">as_data_frame =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To consolidate all trajectory instances into a single dataframe, we’ll vertically bind all 10 imported dataframes using bind_rows() function from tidyverse package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df_trajectories <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(df,df1,df2,df3,df4,df5,df6,df7,df8,df9)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To get a quick overview of the dataset, we’ll first check the number of trajectory instances using <code>dim()</code> function. Then, we’ll use <code>head()</code> function to quickly scan through the data columns and values</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(df_trajectories)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 30329685        9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_trajectories)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  trj_id driving_mode osname  pingtimestamp rawlat rawlng speed bearing accuracy
  &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;           &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;int&gt;    &lt;dbl&gt;
1 70014  car          android    1554943236   1.34   104.  18.9     248      3.9
2 73573  car          android    1555582623   1.32   104.  17.7      44      4  
3 75567  car          android    1555141026   1.33   104.  14.0      34      3.9
4 1410   car          android    1555731693   1.26   104.  13.0     181      4  
5 4354   car          android    1555584497   1.28   104.  14.8      93      3.9
6 32630  car          android    1555395258   1.30   104.  23.2      73      3.9</code></pre>
</div>
</div>
<p>From the result above, we can see that the dataset includes a total of 30329685 trajectory instances, each with a total of 9 columns as follows:</p>
<table class="table">
<thead>
<tr class="header">
<th>Column Name</th>
<th>Data Type</th>
<th>Remark</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>trj_id</td>
<td>chr</td>
<td>Trajectory ID</td>
</tr>
<tr class="even">
<td>driving_mode</td>
<td>chr</td>
<td>Mode of Driving</td>
</tr>
<tr class="odd">
<td>osname</td>
<td>chr</td>
<td></td>
</tr>
<tr class="even">
<td>pingtimestamp</td>
<td>int</td>
<td>Data Recording Timestamp</td>
</tr>
<tr class="odd">
<td>rawlat</td>
<td>num</td>
<td>Latitude Value (WGS-84)</td>
</tr>
<tr class="even">
<td>rawlng</td>
<td>num</td>
<td>Longitude Value (WGS-84)</td>
</tr>
<tr class="odd">
<td>speed</td>
<td>num</td>
<td>Speed</td>
</tr>
<tr class="even">
<td>bearing</td>
<td>int</td>
<td>Bearing</td>
</tr>
<tr class="odd">
<td>accuracy</td>
<td>num</td>
<td>Accuracy</td>
</tr>
</tbody>
</table>
<p>From the above table, it is seen that the <code>pingtimestamp</code> is recorded as <code>int</code>. We need to convert this data to proper datetime format to derive meaningful temporal insights of the data. To do so, we will use <code>as_datetime()</code> function from <code>lubridate</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df_trajectories<span class="sc">$</span>pingtimestamp <span class="ot">&lt;-</span> <span class="fu">as_datetime</span>(df_trajectories<span class="sc">$</span>pingtimestamp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-openstreetmap-road-data-for-malaysia-singapore-and-brunei" class="level3">
<h3 class="anchored" data-anchor-id="importing-openstreetmap-road-data-for-malaysia-singapore-and-brunei">4.3 Importing OpenStreetMap road data for Malaysia, Singapore and Brunei</h3>
<p>The <code>gis_osm_roads_free_1</code> dataset, which we downloaded from OpenStreetMap, is in ESRI shapefile format. To use this data in an R-environment, we need to import it as an sf object. We can do this using the <strong><code>st_read()</code></strong> function of the <strong><code>sf</code></strong> package. This function reads the shapefile data and returns an <strong><code>sf</code></strong> object that can be used for further analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>osm_road_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"~/IS415-GAA/data/geospatial"</span>, </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">layer =</span> <span class="st">"gis_osm_roads_free_1"</span>) <span class="sc">%&gt;%</span> <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `gis_osm_roads_free_1' from data source 
  `/Users/khantminnaing/IS415-GAA/data/geospatial' using driver `ESRI Shapefile'
Simple feature collection with 1764130 features and 10 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 99.66041 ymin: 0.8021131 xmax: 119.2601 ymax: 7.514393
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>After importing the dataset, we will have a quick look at summary of <code>osm_road_sf</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(osm_road_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    osm_id               code         fclass              name          
 Length:1764130     Min.   :5111   Length:1764130     Length:1764130    
 Class :character   1st Qu.:5122   Class :character   Class :character  
 Mode  :character   Median :5141   Mode  :character   Mode  :character  
                    Mean   :5132                                        
                    3rd Qu.:5141                                        
                    Max.   :5199                                        
     ref               oneway             maxspeed           layer        
 Length:1764130     Length:1764130     Min.   :  0.000   Min.   :-5.0000  
 Class :character   Class :character   1st Qu.:  0.000   1st Qu.: 0.0000  
 Mode  :character   Mode  :character   Median :  0.000   Median : 0.0000  
                                       Mean   :  3.146   Mean   : 0.0299  
                                       3rd Qu.:  0.000   3rd Qu.: 0.0000  
                                       Max.   :110.000   Max.   : 5.0000  
    bridge             tunnel                   geometry      
 Length:1764130     Length:1764130     LINESTRING   :1764130  
 Class :character   Class :character   epsg:3414    :      0  
 Mode  :character   Mode  :character   +proj=tmer...:      0  
                                                              
                                                              
                                                              </code></pre>
</div>
</div>
<p>From the code output, we observed that there are a total of <strong>1764130 observations</strong>. This is due to the fact that OpenStreetMap package we downloaded include data for not only Singapore, but also Malaysia and Brunei.</p>
</section>
<section id="importing-singapore-master-plan-planning-subzone-boundary-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-singapore-master-plan-planning-subzone-boundary-data">4.4 Importing Singapore Master Plan Planning Subzone boundary data</h3>
<p>The <code>MP14_SUBZONE_WEB_PL</code> dataset, which we downloaded from <a href="data.gov.sg">data.gov.sg</a>, is in ESRI shapefile format. To use this data in an R-environment, we need to import it as an sf object. We can do this using the <strong><code>st_read()</code></strong> function of the <strong><code>sf</code></strong> package. This function reads the shapefile data and returns an <strong><code>sf</code></strong> object that can be used for further analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mpsz_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"~/IS415-GAA/data/geospatial"</span>, </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">layer =</span> <span class="st">"MP14_SUBZONE_WEB_PL"</span>) <span class="sc">%&gt;%</span> <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `MP14_SUBZONE_WEB_PL' from data source 
  `/Users/khantminnaing/IS415-GAA/data/geospatial' using driver `ESRI Shapefile'
Simple feature collection with 323 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Reflection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Reflection
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the code chunk above, we use <code>%&gt;%</code> operator is used to pipe the output of <code>st_read()</code> to the <code>st_transform()</code> function. Since the dataset we are using is the Singapore boundary, we need to assign the standard coordinate reference system for Singapore, which is SVY21 (EPSG:3414). <code>st_transform()</code> function transforms the coordinate reference system of the <strong><code>sf</code></strong> object to <strong><code>3414</code></strong>.</p>
</div>
</div>
<p>After importing the dataset, we will plot it to see how it looks. The <strong><code>plot()</code></strong> function is used to plot the geometry of the <strong><code>sf</code></strong> object. The <strong><code>st_geometry()</code></strong> function is used to extract the geometry of the <strong><code>mpsz_sf</code></strong> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(mpsz_sf))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="data-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling">5.0 Data Wrangling</h2>
<p>Data wrangling is the process of converting and transforming raw data into a usable form and is carried out prior to conducting any data analysis.</p>
<section id="extracting-trip-starting-locations-and-temporal-data-values-from-grab-posisi-dataset" class="level3">
<h3 class="anchored" data-anchor-id="extracting-trip-starting-locations-and-temporal-data-values-from-grab-posisi-dataset">5.1 Extracting Trip Starting Locations and Temporal Data Values from Grab-Posisi dataset</h3>
<p>Firstly, we will extract trip starting locations for all unqiue trajectories in the dataset and store them to a new df named <code>origin_df</code>. We are also interested in obtaining valuable temporal data such as the day of the week, the hour, and the date (yy-mm-dd). To do so, we will use the following functions from <code>lubridate</code> package, and add the newly derived values as columns to <code>origin_df</code>.</p>
<ul>
<li><p><code>wday</code>: allows us to get days component of a date-time</p></li>
<li><p><code>hour</code>: allows us to get hours component of a date-time</p></li>
<li><p><code>mday</code>: allows us to parse dates with year, month, and day components</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>origin_df <span class="ot">&lt;-</span> df_trajectories <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trj_id) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(pingtimestamp) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">row_number</span>()<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weekday =</span> <span class="fu">wday</span>(pingtimestamp,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">label=</span><span class="cn">TRUE</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">abbr=</span><span class="cn">TRUE</span>),</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">starting_hr =</span> <span class="fu">factor</span>(<span class="fu">hour</span>(pingtimestamp)),</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">day =</span> <span class="fu">factor</span>(<span class="fu">mday</span>(pingtimestamp)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extracting-trip-ending-locations-and-temporal-data-values-from-grab-posisi-dataset" class="level3">
<h3 class="anchored" data-anchor-id="extracting-trip-ending-locations-and-temporal-data-values-from-grab-posisi-dataset">5.2 Extracting Trip Ending Locations and Temporal Data Values from Grab-Posisi dataset</h3>
<p>Similar to what we did in previous session, we are also interested to extract trip ending locations and associated temporal data into a new df called <code>destination_df</code>. We will use the same functions from previous session here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>destination_df <span class="ot">&lt;-</span> df_trajectories <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trj_id) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pingtimestamp)) <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">row_number</span>()<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weekday =</span> <span class="fu">wday</span>(pingtimestamp,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">label=</span><span class="cn">TRUE</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">abbr=</span><span class="cn">TRUE</span>),</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">starting_hr =</span> <span class="fu">factor</span>(<span class="fu">hour</span>(pingtimestamp)),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">day =</span> <span class="fu">factor</span>(<span class="fu">mday</span>(pingtimestamp)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Reflection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Reflection
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>arrange()</code> function sort the timestamps in ascending order by default. Hence, this default order is applied to <code>origin_df</code>. However, for destination_df, the <code>arrange(desc())</code> argument is used to modify the default order to descending.</p>
</div>
</div>
</section>
<section id="converting-to-sf-tibble-data.frame" class="level3">
<h3 class="anchored" data-anchor-id="converting-to-sf-tibble-data.frame">5.3 Converting to sf tibble data.frame</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>origin_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(origin_df,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"rawlng"</span>, <span class="st">"rawlat"</span>),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>destination_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(destination_df,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"rawlng"</span>, <span class="st">"rawlat"</span>),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="creating-a-coastalline-of-singapore" class="level3">
<h3 class="anchored" data-anchor-id="creating-a-coastalline-of-singapore">5.4 Creating a CoastalLine of Singapore</h3>
<p>The original <code>mpsz_sf</code> dataset we imported include information of all URA Master Plan planning area boundaries. However, for this analysis, we only need the national-level boundary of Singapore. Hence, we will need to union all the subzone boundaries to one single polygon boundary. Also, Grab ride-hailing service is only available on the main Singapore islands. Hence, we will need to remove outer islands which Grab service is not available. In particular, we will remove the following planning subzones: <code>NORTH-EASTERN ISLANDS</code>, <code>SOUTHERN GROUP</code>, <code>SUDONG</code> &amp; <code>SEMAKAU</code>.</p>
<p>We can remove these subzones using the <strong><code>subset()</code></strong> function. The subset() function is used to extract rows from a data frame that meet certain conditions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>northeasten.islands <span class="ot">&lt;-</span> <span class="fu">subset</span>(mpsz_sf, mpsz_sf<span class="sc">$</span>SUBZONE_N <span class="sc">==</span> <span class="st">"NORTH-EASTERN ISLANDS"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>southern.islands <span class="ot">&lt;-</span> <span class="fu">subset</span>(mpsz_sf, mpsz_sf<span class="sc">$</span>SUBZONE_N <span class="sc">==</span> <span class="st">"SOUTHERN GROUP"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>sudong <span class="ot">&lt;-</span> <span class="fu">subset</span>(mpsz_sf, mpsz_sf<span class="sc">$</span>SUBZONE_N <span class="sc">==</span> <span class="st">"SUDONG"</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>semakau <span class="ot">&lt;-</span> <span class="fu">subset</span>(mpsz_sf,mpsz_sf<span class="sc">$</span>SUBZONE_N <span class="sc">==</span> <span class="st">"SEMAKAU"</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>outerislands <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(<span class="fu">list</span>(northeasten.islands,southern.islands,sudong,semakau))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Reflection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Reflection
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the code chunk above, we first created four new data frames called <code>northeasten.islands</code>, <code>southern.islands</code>, <code>sudong</code>, and <code>semakau</code> by selecting rows from <code>mpsz_sf</code> where the value in the <code>SUBZONE_N</code> column matches the corresponding value.</p>
<p>After that, we used <code>bind_rows()</code> function from the <strong>dplyr</strong> package to combine these four data frames into a single data frame called <code>outerislands</code>.</p>
</div>
</div>
<p>After importing the dataset, we will plot it to see how it looks.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(outerislands))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As mentioned earlier, we only need to get national-level boundary of Singapore, without outer islands. To do so, we will need to process the mpsz_sf layer to achieve the outcome. - We will first use <code>st_union()</code> function from the <strong>sf</strong> package to combine the geometries of <code>mpsz_sf</code> and <code>outerislands</code> sf objects into a single geometry each. - Next, we will use <code>st_difference()</code> function then removes the overlapping areas between the two geometries. - Finally, we will store the non-overlapping areas into a new sf objected called <code>sg_sf</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>sg_sf <span class="ot">&lt;-</span> <span class="fu">st_difference</span>(<span class="fu">st_union</span>(mpsz_sf), <span class="fu">st_union</span>(outerislands))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To assess whether the geometry of the newly created <code>sg_sf</code> matches our intended outcome, we will plot it out.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(sg_sf))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="extracting-road-layers-within-singapore" class="level3">
<h3 class="anchored" data-anchor-id="extracting-road-layers-within-singapore">5.5 Extracting Road Layers within Singapore</h3>
<p>As we have seen in Section 4.3., <code>osm_road_sf</code> dataset includes road networks from not only Singapore, but also Malaysia and Brunei. However, our analysis is focused on Singapore. Hence, we will need to remove unecessary data rows. To do so, we will</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#sg_road_sf &lt;- st_difference(osm_road_sf,sg_sf)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(sg_road_sf)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="converting-the-simple-features-to-planar-point-pattern-object" class="level3">
<h3 class="anchored" data-anchor-id="converting-the-simple-features-to-planar-point-pattern-object">5.5 Converting the Simple Features to Planar Point Pattern Object</h3>
<p>In order to use the capabilities of spatstat packahe, a spatial dataset should be converted into an object of class planar point pattern <code>ppp</code> (Baddeley et al., 2015). A point pattern object contains the spatial coordinates of the points, the marks attached to the points (if any), the window in which the points were observed, and the name of the unit of length for the spatial coordinates. s. Thus, a single object of class <code>ppp</code> contains all the information required to perform spatial point pattern analysis.</p>
<p>In previous section, we have created sf objects of Grab trajectory origin and destination points. Now, we will convert them into ppp objects using <a href="https://www.rdocumentation.org/packages/spatstat/versions/1.64-1/topics/as.ppp"><code>as.ppp()</code></a> function from <strong>spatstat</strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>origin_ppp <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(<span class="fu">st_coordinates</span>(origin_sf), <span class="fu">st_bbox</span>(origin_sf))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(origin_ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The code chunk above converts the <strong><code>origin_sf</code></strong> object to a point pattern object of class <strong><code>ppp</code>.</strong> <strong><code>st_coordinates()</code></strong> function is used to extract the coordinates of the <strong><code>origin_sf</code></strong> object and <strong><code>st_bbox()</code></strong> function is used to extract the bounding box of the <strong><code>origin_sf</code></strong> object. The resulting object <code>origin_ppp</code> is a point pattern object of class <code>ppp</code>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>destination_ppp <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(<span class="fu">st_coordinates</span>(destination_sf), <span class="fu">st_bbox</span>(destination_sf))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(destination_ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="handling-data-errors" class="level3">
<h3 class="anchored" data-anchor-id="handling-data-errors">5.6 Handling Data Errors</h3>
<p>Before going striaght into analysis, we will need to a quick look at the summary statistics of the newly created ppp objects. This is an important step to ensure that the data is free of errors and that a reliable analysis can be performed.</p>
<section id="data-error-handling-for-origin_ppp" class="level4">
<h4 class="anchored" data-anchor-id="data-error-handling-for-origin_ppp">5.6.1 Data Error Handling for <code>origin_ppp</code></h4>
<p>We will use <code>summary()</code> function to get summary information of <code>origin_ppp</code> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(origin_ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  28000 points
Average intensity 2.473666e-05 points per square unit

Coordinates are given to 3 decimal places
i.e. rounded to the nearest multiple of 0.001 units

Window: rectangle = [3628.24, 49845.23] x [25198.14, 49689.64] units
                    (46220 x 24490 units)
Window area = 1131920000 square units</code></pre>
</div>
</div>
<p>We can also check if there is any duplicated points in <code>origin_ppp</code> object using <code>any(duplicated()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">duplicated</span>(origin_ppp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>The code output is <strong><code>FALSE</code></strong>, which means there are no duplication of point coordaintes in the <strong><code>origin_ppp</code></strong> object.</p>
<div class="call-tip" title="Reflection">
<p><strong>Why do we need to check duplication?</strong></p>
<p>When analyzing spatial point processes, it is important to avoid duplication of points. This is because statistical methodology for spatial point processes is based largely on the assumption that processes are simple, i.e., that points of the process can never be coincident. When the data have coincident points, some statistical procedures designed for simple point processes will be severely affected (Baddeley et al., 2015).</p>
</div>
</section>
<section id="data-error-handling-for-destination_ppp" class="level4">
<h4 class="anchored" data-anchor-id="data-error-handling-for-destination_ppp">5.6.2 Data Error Handling for <code>destination_ppp</code></h4>
<p>We will use <code>summary()</code> function to get summary information of <code>destination_ppp</code> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(destination_ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  28000 points
Average intensity 2.493661e-05 points per square unit

Coordinates are given to 3 decimal places
i.e. rounded to the nearest multiple of 0.001 units

Window: rectangle = [3637.21, 49870.63] x [25221.3, 49507.79] units
                    (46230 x 24290 units)
Window area = 1122850000 square units</code></pre>
</div>
</div>
<p>We can also check if there is any duplicated points in <code>destination_ppp</code> object using <code>any(duplicated()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">duplicated</span>(destination_ppp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>The code output is <strong><code>FALSE</code></strong>, which means there are no duplication of point coordinates in the <strong><code>destination_ppp</code></strong> object.</p>
</section>
</section>
<section id="creating-observation-windows" class="level3">
<h3 class="anchored" data-anchor-id="creating-observation-windows">5.7 Creating Observation Windows</h3>
<p>Many data types in <strong>spatstat</strong> require us to specify the region of space inside which the data were observed. This is the observation window and it is represented by an object of class <code>owin</code>. In this analysis, our study area is Singapore, hence we will use Singapore boundary as the observation window for spatial point pattern analysis.</p>
<p>In Section 5.4, we have already created the <code>sg_sf</code> object, which represents the Singapore boundary (without outer islands). To convert this sf object to <code>owin</code> object, we will use <a href="https://www.rdocumentation.org/packages/spatstat/versions/1.64-1/topics/owin.object"><code>as.owin()</code></a> function from <strong>spatstat</strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>sg_owin <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(sg_sf)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.owin</span>(sg_owin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We will use <code>summary()</code> function to get summary information of <code>sg_owin</code> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sg_owin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Window: polygonal boundary
44 separate polygons (24 holes)
                  vertices         area relative.area
polygon 1            14651  6.97996e+08      9.92e-01
polygon 2 (hole)         3 -2.21090e+00     -3.14e-09
polygon 3              285  1.61128e+06      2.29e-03
polygon 4 (hole)         3 -2.05920e-03     -2.93e-12
polygon 5 (hole)         3 -8.83647e-03     -1.26e-11
polygon 6               27  1.50315e+04      2.14e-05
polygon 7 (hole)        36 -4.01660e+04     -5.71e-05
polygon 8 (hole)       317 -5.11280e+04     -7.27e-05
polygon 9 (hole)         3 -2.89050e-05     -4.11e-14
polygon 10              30  2.80002e+04      3.98e-05
polygon 11 (hole)        3 -2.83151e-01     -4.03e-10
polygon 12              71  8.18750e+03      1.16e-05
polygon 13 (hole)        3 -1.68316e-04     -2.39e-13
polygon 14 (hole)       36 -7.79904e+03     -1.11e-05
polygon 15 (hole)        4 -2.05611e-02     -2.92e-11
polygon 16 (hole)        3 -2.18000e-06     -3.10e-15
polygon 17 (hole)        3 -3.65501e-03     -5.20e-12
polygon 18 (hole)        3 -4.95057e-02     -7.04e-11
polygon 19 (hole)        3 -3.99521e-02     -5.68e-11
polygon 20 (hole)        3 -6.62377e-01     -9.42e-10
polygon 21 (hole)        3 -2.09065e-03     -2.97e-12
polygon 22              91  1.49663e+04      2.13e-05
polygon 23 (hole)       26 -1.25665e+03     -1.79e-06
polygon 24 (hole)      349 -1.21433e+03     -1.73e-06
polygon 25 (hole)       20 -4.39069e+00     -6.24e-09
polygon 26 (hole)       48 -1.38338e+02     -1.97e-07
polygon 27 (hole)       28 -1.99862e+01     -2.84e-08
polygon 28              40  1.38607e+04      1.97e-05
polygon 29 (hole)       40 -6.00381e+03     -8.54e-06
polygon 30 (hole)        7 -1.40545e-01     -2.00e-10
polygon 31 (hole)       12 -8.36709e+01     -1.19e-07
polygon 32              45  2.51218e+03      3.57e-06
polygon 33             142  3.22293e+03      4.58e-06
polygon 34             148  3.10395e+03      4.41e-06
polygon 35              75  1.73526e+04      2.47e-05
polygon 36              83  5.28920e+03      7.52e-06
polygon 37             106  3.04104e+03      4.32e-06
polygon 38             266  1.50631e+06      2.14e-03
polygon 39              71  5.63061e+03      8.01e-06
polygon 40              10  1.99717e+02      2.84e-07
polygon 41             478  2.06120e+06      2.93e-03
polygon 42              65  8.42861e+04      1.20e-04
polygon 43              47  3.82087e+04      5.43e-05
polygon 44              22  6.74651e+03      9.59e-06
enclosing rectangle: [2667.54, 55941.94] x [21494.3, 50256.33] units
                     (53270 x 28760 units)
Window area = 703317000 square units
Fraction of frame area: 0.459</code></pre>
</div>
</div>
</section>
<section id="combining-ppp-objects-and-owin-object" class="level3">
<h3 class="anchored" data-anchor-id="combining-ppp-objects-and-owin-object"><strong>5.8 Combining <code>ppp</code> objects and <code>owin</code> object</strong></h3>
<p>In section 5.5, we have created two <code>ppp</code> objects - <code>origin_ppp</code> and <code>destination_ppp</code>, each representing the spatial points of Grab trajectory origin and destination. In section 5.7, we have created a <code>owin</code> object called <code>sg_owin</code>, which represent the observation window of our analysis.</p>
<p>The observation window <code>sg_owin</code> and the point pattern <code>origin_ppp</code> or <code>destination_ppp</code> can be combined, so that the custom window replaces the default ractangular extent (as seen in section 5.5).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>origin_ppp_sg <span class="ot">=</span> origin_ppp[sg_owin]</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>destination_ppp_sg <span class="ot">=</span> destination_ppp[sg_owin]</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(origin_ppp_sg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(destination_ppp_sg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-27-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We will use <code>summary()</code> function to get summary information of the newly created <code>origin_ppp_sg</code> object and <code>destination_ppp_sg</code> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(origin_ppp_sg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  28000 points
Average intensity 3.981136e-05 points per square unit

Coordinates are given to 3 decimal places
i.e. rounded to the nearest multiple of 0.001 units

Window: polygonal boundary
44 separate polygons (24 holes)
                  vertices         area relative.area
polygon 1            14651  6.97996e+08      9.92e-01
polygon 2 (hole)         3 -2.21090e+00     -3.14e-09
polygon 3              285  1.61128e+06      2.29e-03
polygon 4 (hole)         3 -2.05920e-03     -2.93e-12
polygon 5 (hole)         3 -8.83647e-03     -1.26e-11
polygon 6               27  1.50315e+04      2.14e-05
polygon 7 (hole)        36 -4.01660e+04     -5.71e-05
polygon 8 (hole)       317 -5.11280e+04     -7.27e-05
polygon 9 (hole)         3 -2.89050e-05     -4.11e-14
polygon 10              30  2.80002e+04      3.98e-05
polygon 11 (hole)        3 -2.83151e-01     -4.03e-10
polygon 12              71  8.18750e+03      1.16e-05
polygon 13 (hole)        3 -1.68316e-04     -2.39e-13
polygon 14 (hole)       36 -7.79904e+03     -1.11e-05
polygon 15 (hole)        4 -2.05611e-02     -2.92e-11
polygon 16 (hole)        3 -2.18000e-06     -3.10e-15
polygon 17 (hole)        3 -3.65501e-03     -5.20e-12
polygon 18 (hole)        3 -4.95057e-02     -7.04e-11
polygon 19 (hole)        3 -3.99521e-02     -5.68e-11
polygon 20 (hole)        3 -6.62377e-01     -9.42e-10
polygon 21 (hole)        3 -2.09065e-03     -2.97e-12
polygon 22              91  1.49663e+04      2.13e-05
polygon 23 (hole)       26 -1.25665e+03     -1.79e-06
polygon 24 (hole)      349 -1.21433e+03     -1.73e-06
polygon 25 (hole)       20 -4.39069e+00     -6.24e-09
polygon 26 (hole)       48 -1.38338e+02     -1.97e-07
polygon 27 (hole)       28 -1.99862e+01     -2.84e-08
polygon 28              40  1.38607e+04      1.97e-05
polygon 29 (hole)       40 -6.00381e+03     -8.54e-06
polygon 30 (hole)        7 -1.40545e-01     -2.00e-10
polygon 31 (hole)       12 -8.36709e+01     -1.19e-07
polygon 32              45  2.51218e+03      3.57e-06
polygon 33             142  3.22293e+03      4.58e-06
polygon 34             148  3.10395e+03      4.41e-06
polygon 35              75  1.73526e+04      2.47e-05
polygon 36              83  5.28920e+03      7.52e-06
polygon 37             106  3.04104e+03      4.32e-06
polygon 38             266  1.50631e+06      2.14e-03
polygon 39              71  5.63061e+03      8.01e-06
polygon 40              10  1.99717e+02      2.84e-07
polygon 41             478  2.06120e+06      2.93e-03
polygon 42              65  8.42861e+04      1.20e-04
polygon 43              47  3.82087e+04      5.43e-05
polygon 44              22  6.74651e+03      9.59e-06
enclosing rectangle: [2667.54, 55941.94] x [21494.3, 50256.33] units
                     (53270 x 28760 units)
Window area = 703317000 square units
Fraction of frame area: 0.459</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(destination_ppp_sg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  27997 points
Average intensity 3.980709e-05 points per square unit

Coordinates are given to 3 decimal places
i.e. rounded to the nearest multiple of 0.001 units

Window: polygonal boundary
44 separate polygons (24 holes)
                  vertices         area relative.area
polygon 1            14651  6.97996e+08      9.92e-01
polygon 2 (hole)         3 -2.21090e+00     -3.14e-09
polygon 3              285  1.61128e+06      2.29e-03
polygon 4 (hole)         3 -2.05920e-03     -2.93e-12
polygon 5 (hole)         3 -8.83647e-03     -1.26e-11
polygon 6               27  1.50315e+04      2.14e-05
polygon 7 (hole)        36 -4.01660e+04     -5.71e-05
polygon 8 (hole)       317 -5.11280e+04     -7.27e-05
polygon 9 (hole)         3 -2.89050e-05     -4.11e-14
polygon 10              30  2.80002e+04      3.98e-05
polygon 11 (hole)        3 -2.83151e-01     -4.03e-10
polygon 12              71  8.18750e+03      1.16e-05
polygon 13 (hole)        3 -1.68316e-04     -2.39e-13
polygon 14 (hole)       36 -7.79904e+03     -1.11e-05
polygon 15 (hole)        4 -2.05611e-02     -2.92e-11
polygon 16 (hole)        3 -2.18000e-06     -3.10e-15
polygon 17 (hole)        3 -3.65501e-03     -5.20e-12
polygon 18 (hole)        3 -4.95057e-02     -7.04e-11
polygon 19 (hole)        3 -3.99521e-02     -5.68e-11
polygon 20 (hole)        3 -6.62377e-01     -9.42e-10
polygon 21 (hole)        3 -2.09065e-03     -2.97e-12
polygon 22              91  1.49663e+04      2.13e-05
polygon 23 (hole)       26 -1.25665e+03     -1.79e-06
polygon 24 (hole)      349 -1.21433e+03     -1.73e-06
polygon 25 (hole)       20 -4.39069e+00     -6.24e-09
polygon 26 (hole)       48 -1.38338e+02     -1.97e-07
polygon 27 (hole)       28 -1.99862e+01     -2.84e-08
polygon 28              40  1.38607e+04      1.97e-05
polygon 29 (hole)       40 -6.00381e+03     -8.54e-06
polygon 30 (hole)        7 -1.40545e-01     -2.00e-10
polygon 31 (hole)       12 -8.36709e+01     -1.19e-07
polygon 32              45  2.51218e+03      3.57e-06
polygon 33             142  3.22293e+03      4.58e-06
polygon 34             148  3.10395e+03      4.41e-06
polygon 35              75  1.73526e+04      2.47e-05
polygon 36              83  5.28920e+03      7.52e-06
polygon 37             106  3.04104e+03      4.32e-06
polygon 38             266  1.50631e+06      2.14e-03
polygon 39              71  5.63061e+03      8.01e-06
polygon 40              10  1.99717e+02      2.84e-07
polygon 41             478  2.06120e+06      2.93e-03
polygon 42              65  8.42861e+04      1.20e-04
polygon 43              47  3.82087e+04      5.43e-05
polygon 44              22  6.74651e+03      9.59e-06
enclosing rectangle: [2667.54, 55941.94] x [21494.3, 50256.33] units
                     (53270 x 28760 units)
Window area = 703317000 square units
Fraction of frame area: 0.459</code></pre>
</div>
</div>
</section>
</section>
<section id="exploratory-spatial-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-spatial-data-analysis">6.0 Exploratory Spatial Data Analysis</h2>
<section id="visualising-frequency-distribution" class="level3">
<h3 class="anchored" data-anchor-id="visualising-frequency-distribution">6.1 Visualising Frequency Distribution</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>origin_df, </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>weekday)) <span class="sc">+</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>origin_df, </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>day)) <span class="sc">+</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-29-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="creating-point-symbol-maps" class="level3">
<h3 class="anchored" data-anchor-id="creating-point-symbol-maps">6.2 Creating Point Symbol Maps</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"view"</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(origin_sf) <span class="sc">+</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_dots</span>(<span class="at">alpha=</span><span class="fl">0.4</span>, </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">size=</span><span class="fl">0.05</span>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(destination_sf) <span class="sc">+</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_dots</span>(<span class="at">alpha=</span><span class="fl">0.4</span>, </span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">size=</span><span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>1. Rey, S.J., Arribas-Bel, D., Wolf, L.J.: Point Pattern Analysis. In: Geographic Data Science with python. pp.&nbsp;185–219. CRC Press, Boca Raton etc. (2023).</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>