project:
  type: website

website:
  title: "IS415 - Geospatial with Khant"
  navbar:
    left:
      - text: "In-Class Exercises"
        menu:
        - href: In-class_Ex/In-class_Ex02.qmd
        - href: In-class_Ex/In-class_Ex03.qmd
        - href: In-class_Ex/In-class_Ex03-NKDE.qmd
        - href: In-class_Ex/In-class_Ex04.qmd
        - href: In-class_Ex/In-class_Ex05.qmd
      - text: "Hands-On Exercises"
        menu:
        - href: Hands-on_Ex/hands_on1.qmd
          text: "Hands-On Exercise 1"
        - href: Hands-on_Ex/hands_on02.qmd
          text: "Hands-On Exercise 2"
        - href: Hands-on_Ex/hands_on03.qmd
          text: "Hands-On Exercise 3"
        - href: Hands-on_Ex/hands_on04.qmd
          text: "Hands-On Exercise 4"
        - href: Hands-on_Ex/hands_on05.qmd
          text: "Hands-On Exercise 5"
        - href: Hands-on_Ex/hands_on057.qmd
          text: "Hands-On Exercise 7"
      - text: "Take-home Exercises"
        menu:
        - href: Take-home_Ex/Take-home_Ex01.qmd
          text: "Take-home Exercise 1"
        - href: Take-home_Ex/Take-home_Ex02/Take-home_Ex02.qmd
          text: "Take-home Exercise 2"

    right:
      - href: index.qmd
        text: Home
      - about.qmd
page-footer:
  background: primary
  left: "Geosaptial Analytics - Where Data Meets Geograpyhy"

format:
  html:
    theme: [flatly, dark.scss]
    css: styles.css
    toc: true
    
editor: visual

