project:
  type: website

website:
  title: "IS415 - Geospatial with Khant"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "In-Class Exercises"
        menu:
        - href: In-class_Ex/In-class_Ex01.qmd
      - text: "Hands-On Exercises"
        menu:
        - href: Hands-on_Ex/hands_on1.qmd
          text: "Hands-On Exercise 1"
        - href: Hands-on_Ex/hands_on08.qmd
          text: "Hands-On Exercise 8"

page-footer:
  background: primary
  left: "Geosaptial Analytics - Where Data Meets Geograpyhy"

format:
  html:
    theme: united
    css: styles.css
    toc: true
    
editor: visual

