project:
  type: website

website:
  title: "IS415 - Khant"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Hands-On Exercises"
        menu:
        - href: hands_on_exercises/hands_on1.qmd
          text: "Hands-On Exercise 1"

page-footer:
    background: primary
    left: "Geosaptial Analytics - Where Data Meets Geograpyhy"

format:
  html:
    theme: united
    css: styles.css
    toc: true
    
editor: visual

